service: bcp-serverless-event
useDotenv: true

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-southeast-1
  httpApi:
    cors: true

functions:
  inboxMessage:
    handler: handler.inboxMessage
    events:
      - httpApi:
          method: POST
          path: /api/inbox_custom

plugins:
  - serverless-prune-plugin
