service: bcp-serverless-event
useDotenv: true

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: ap-southeast-1
  httpApi:
    cors: true
  environment:
    userAmity : ${env.userAmity}
    passwordAmity : ${env.passwordAmity}
    clientId : ${env.clientId}
    cloud : ${env.cloud}
    cognito : ${env.cognito}
    sfDomain : ${env.sfDomain}
    sfClientId : ${env.sfClientId}
    sfClientSecret : ${env.sfClientSecret}
    sfUserName : ${env.sfUserName}
    sfPassword : ${env.sfPassword}
    line_token : ${env.line_token}
    line_domain : ${env.line_domain}
    s3Bucket : ${env.s3Bucket}
    aws_key: ${env.aws_key}
    aws_secret: ${env.aws_secret}
    
functions:
  inboxMessage:
    handler: handler.inboxMessage
    events:
      - httpApi:
          method: POST
          path: /api/inbox_custom


  outMessage:
    handler: outbox-handler.outboxMessage
    events:
      - httpApi:
          method: POST
          path: /api/outbox_custom

plugins:
  - serverless-prune-plugin
  - serverless-dotenv-plugin